version: "3.8"

services:
  jupiter:
    build:
      context: .
      dockerfile: docker/src/jupiter/DOCKERFILE
    ports:
    - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"
    volumes:
      - "./:/home/jovyan/work:rw"
      # - "./docker/src/display_.py:/opt/.pycharm_helpers/pycharm_display/datalore/display/display_.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu, utility ]
    devices:
      - /dev/nvidiactl:/dev/nvidiactl:mrw
      - /dev/nvidia0:/dev/nvidia0:mrw