= Data Science in Techno-Socio-Economic Systems
Matthias Baumann <matthias-baumann@outlook.com>
v0.1: First draft

The project features mass-data accumulation through an IoT Sensor, Warehousing and Processing. The future idea of usage is to integrate the measured data with additional datasets.


:stem:
:lang: en
:icons: font
:awestruct-layout:base
:toc: right
:experimental:

== Installation
The installation is prepared for Linux systems in anaconda.sh. If you have an Windows computer just use Anaconda, download the installer from anaconda.com[anaconda website].

WARNING: Currently, installing RPy2 failes under the Linux environment (others were not tested). Do not try! It is not worth your time, since conda makes faults in the installation
procedure. Furthermore, changing python versions, as suggested by the tool, does not help your case, even though it looks promising at first. Further, investigation is already
underway with Nico.

== Running

[source,shell]
----
conda activate stes
jupyter notebook
----

The browser should start and present you the notebooks, in the directory your currently in, and let's you select one.

TIP: Select under kbd:[kernel] -> kbd:[change kernel] -> kbd:[stes], this activates the user installed kernel, which ensures that you definitely are in
the venv while you execute stuff in the notebook. If you do not see that kernel, check whether your in the venv (stes).

== Documentation

You can find the documentation in the /docs directory.

== Publish

We could publish our Stuff as an interactive Website on https://mybinder.org/.